# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ea269d75c9edcc0a0f6533afcda5747460b524d26c2a52e1423e132ce7dc8f71b98f0f50ae9f4182aa62025cdd74eeaa32f6484184a78d12fe7518fc0df768

test:
  secret_key_base: 640e1d65f11543020f7e7be9db29072bc5ac630f188d5f6631401b672e8bcdaffc6328dbabfef1e902c80e47e3cc6908bc87ed636498b429c7c142f079a638ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
